name: Check Contract Version

on:
  pull_request:
    paths:
      - 'contracts/plutus.json'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if plutus.json changed
        id: plutus_changed
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'contracts/plutus.json'; then
            echo "::set-output name=plutus_changed::true"
          else
            echo "::set-output name=plutus_changed::false"
          fi

      - name: Extract version from aiken.toml (base)
        id: base_version
        run: |
          base_version=$(git show ${{ github.event.before }}:contracts/aiken.toml | grep -oP '(?<=version = ").*(?=")' | head -n 1)
          echo "::set-output name=base_version::$base_version"

      - name: Extract version from aiken.toml (head)
        id: head_version
        run: |
          head_version=$(grep -oP '(?<=version = ").*(?=")' contracts/aiken.toml | head -n 1)
          echo "::set-output name=head_version::$head_version"

      - name: Compare versions and fail if necessary
        if: steps.plutus_changed.outputs.plutus_changed == 'true' && steps.base_version.outputs.base_version == steps.head_version.outputs.head_version
        run: |
          echo "onchain scripts changed but aiken.toml version did not change. Failing the build."
          echo "Run pnpm contracts:bump:{major|minor|patch} script to update the version on the PR"
          exit 1

      - name: Success message
        if: steps.contracts_changed.outputs.contracts_changed == 'true' && steps.base_version.outputs.base_version != steps.head_version.outputs.head_version
        run: |
          echo "Both contracts.json changed and aiken.toml version updated."
