name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.20-alpha
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: aiken fmt --check aiken
      - run: aiken check -D aiken
      - run: deno task build 

